cd fxk-boot-dependencies
mvn clean
cd ../fxk-boot-parent
mvn clean
cd ../fxk-boot-starter-redis
mvn clean
cd ../fxk-boot-starter-mybatis-plus
mvn clean
cd ../fxk-boot-security-oauth2
mvn clean
cd ../fxk-boot-starter-admin
mvn clean
cd ../fxk-boot-starter-distributed-lock
mvn clean
cd ../fxk-boot-starter-elasticsearch
mvn clean
cd ../fxk-boot-starter-enum
mvn clean
cd ../fxk-boot-starter-generator
mvn clean
cd ../fxk-boot-starter-log
mvn clean
cd ../fxk-boot-starter-springfox
mvn clean
cd ../fxk-boot-starter-websocket
mvn clean
cd ../fxk-boot-starter-xxl-mq
mvn clean
cd ../fxk-boot-mqbroker
mvn clean
cd ../fxk-boot-canal
mvn clean
