fxk:
  canal:
    redis:
      configuration:
        instance: canalRedisExample
        filter: canal_client_example.t_user
        show-entry-log: true
        show-event-log: true
        batch-size: 10000
      enabled: true