fxk:
  canal:
    redis:
      configuration:
        instance: canalRedisExample
        filter: canal_client_example.t_user
        show-entry-log: true
        show-event-log: true
        batch-size: 10000
        cluster:
          nodes: localhost:3181,localhost:3182,localhost:3183
      enabled: true