spring:
  datasource:
    url: jdbc:mysql://${code-generator.ip}:${code-generator.port}/${code-generator.schema}?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
    username: ${code-generator.username}
    password: ${code-generator.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

# 代码生成配置
code-generator:
  # 数据库 IP
  ip: localhost
  # 数据库端口
  port: 3306
  # 数据库
  schema: code_generator
  # 账号
  username: root
  # 密码
  password: 123456
  # 需要生成的表
  tables: t_user
  # 作者
  author: fanxuankai
  # 去表前缀
  prefix: t_
  # 项目绝对路径
  project-dir: /Users/fanxuankai/Java/Workspace/myproject/fanxuankai/framework/标准/fxk-boot/fxk-boot-starter-generator-sample
  # API 相对路径
  api-path:
  # WEB 相对路径
  web-path:
  # 服务名
  service-name: user-service
  # 包名
  package-name: com.fanxuankai.boot.generator
  # 是否覆盖
  cover: true
  # 自动填值 { 列名: INSERT|UPDATE|INSERT_UPDATE }
  auto-fill:
    create_user_id: INSERT
    create_date: INSERT
    modified_user_id: UPDATE
    last_modified_date: UPDATE
    deleted: INSERT
  # dto 不显示的字段
  form-exclude-columns: create_user_id,create_date,modified_user_id,last_modified_date,deleted
  # vo 不显示的字段
  list-exclude-columns: deleted
  # 父类字段
  inherited-columns: id,create_user_id,create_date,modified_user_id,last_modified_date,deleted
  # 数据库类型转 Java 类型
  column-type-mapping:
    bigint: Long
    bit: Boolean
    char: String
    date: Date
    datetime: Date
    decimal: BigDecimal
    double: Double
    float: Float
    int: Integer
    integer: Integer
    longtext: String
    mediumint: Integer
    mediumtext: String
    smallint: Integer
    text: String
    timestamp: Timestamp
    tinyint: Integer
    tinytext: String
    varchar: String