spring:
  datasource:
    url: jdbc:clickhouse://192.168.173.201:8123
    driver-class-name: ru.yandex.clickhouse.ClickHouseDriver
fxk:
  canal:
    clickhouse:
      configuration:
        instance: canalClickhouseExample
        filter: clickhouse_demo.user,clickhouse_demo.dept,clickhouse_demo.post
        show-entry-log: false
        show-event-log: true
        batch-size: 100
        parallel: true
        merge-entry:
          merge: true
          max-row-data-size:
            INSERT: 1000
            UPDATE: 10000
            DELETE: 10000
        skip: false
      enabled: true
      consumer-config-map:
        clickhouse_demo:
          user:
            ignore-change-columns: date
          dept:
            ignore-change-columns: date
          post:
            ignore-change-columns: date
      schema-name: default