spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${fxk.code-generator.schema}?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
fxk:
  # 代码生成配置
  code-generator:
    # 激活
    enabled: false
    # 数据库
    schema: fxk-boot
    # 需要生成的表
    tables: user
    # 作者
    author: admin
    # 去表前缀
    prefix: t_
    # 项目绝对路径
    project-dir: /Users/fanxuankai/Java/Workspace/myproject/fanxuankai/framework/标准/fxk-boot/fxk-boot-example/fxk-boot-starter-generator-example
    # API 相对路径
    api-path:
    # WEB 相对路径
    web-path:
    # 服务名
    service-name: user-service
    # 包名
    package-name: com.fanxuankai.boot.generator
    # 要生成的类文件
    files-to-create:
    # 集成 EasyExcel
    integrate-easy-excel: true