server:
  port: 8081
logging:
  level:
    org:
      springframework:
        security:
          oauth2: debug
security:
  oauth2:
    resource:
      jwt:
        key-store: classpath:mytest.jks
        key-alias: mytest
        key-password: mypass
        key-store-password: mypass